config/routes.rb
Rails.application.routes.draw do
  resources :photos
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :articles do
  	resources :comments
  end

  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
	             length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/photo.rb
class Photo < ApplicationRecord
	include ImageUploader::Attachment.new(:image)
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	def author?
		self.role == 'author'
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

    def require_user
    end

	def require_author
		redirect_to '/' unless current_user.author?
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	# http_basic_authenticate_with  name: 'dhh', password: 'secret', except: [:index, :show]

    before_action :require_user, only: [:index]

    before_action :require_author, only: [:edit, :update, :destroy]

	def index
		@articles = Article.all
	end

    def show
    	@article = Article.find(params[:id])
    end

	def new
		@article = Article.new
	end


    def edit
		@article = Article.find(params[:id])
	end

	def create
		@article = Article.new(article_params)

		if @article.save
		 redirect_to @article
		else
			render 'new'
		end
	end



	def update
		  @article = Article.find(params[:id])

		  if @article.update(article_params)
		    redirect_to @article
		  else
		    render 'edit'
		  end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end
    
    private
      def article_params
      	params.require(:article).permit(:title, :text)
      end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	http_basic_authenticate_with  name: 'dhh', password: 'secret', only: :destroy
	
	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy
		redirect_to article_path(@article)
	end

	private
	   def comment_params
	   	  params.require(:comment).permit(:comment, :body)
	   end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:image)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		@user = User.find_by_email(params[:session][:email])

		if @user && @user.authenticate(params[:session][:password])
			session[:user_id] = @user.id
			redirect_to '/'
		else
			redirect_to 'login'
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to '/'
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
          redirect_to '/'
        else
          redirect_to 'signup'
        end
	end

	private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :password)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title, id: :article_title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text, id: :article_body %>
    <trix-editor input="article_body"></trix-editor>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>

<%= link_to 'New article', new_article_path %>
<table>
	<tr>
		<th>Title</th>
		<th>Text</th>
		<th colspan="3"></th>
	</tr>

	<% @articles.each do |article| %>
	  <tr>
	  	<td><%= article.title %></td>
	  	<td><%= article.text %></td>
	  	<td><%= link_to 'Show', article_path(article) %></td>
	  	<td><%= link_to 'Edit', edit_article_path(article) %></td>
	  	<td><%= link_to 'Destroy', article_path(article),
	  	        method: :delete,
	  	        data: { confirm: 'Are you sure?' } %></td>
	  </tr>
	<% end %>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= sanitize @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>



<% if current_user && current_user.author? %>
   <%= link_to 'Edit', edit_article_path(@article) %> |
   <%= link_to 'Delete', article_path(@article), method: 'delete' %>
<% end %>


<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
	<strong>Commenter:</strong>
	<%= comment.commenter %>
</p>

<p>
	<strong>Comment:</strong>
	<%= comment.body %>
</p>

<p>
	<%= link_to 'Destroy Comment', [comment.article, comment],
	            method: :delete,
	            data: { confirm: 'Are you sure?'} %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [@article, @article.comments.build ], local: true ) do |form| %>
	<p>
	   <%= form.label :commenter %>
	   <%= form.text_field :commenter %>
	</p>

	<p>
	   <%= form.label :body %><br>
	   <%= form.text_area :body %>
	</p>

	<p>
	   <%= form.submit %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <% if current_user %>
      <ul>
        <li><%= current_user.email %></li>
        <li><%= link_to "Log out", logout_path, method: "delete" %></li>
      </ul>
    <% else %>
      <ul>
        <li><%= link_to "Login", 'login' %></li>
        <li><%= link_to "Signup", 'signup' %></li>
      </ul>
    <% end %>

  </body>
</html>

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photos</h1>

<table>
  <thead>
    <tr>
      <th>Image data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.image_data %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @photo.image_url %>

<p>
  <strong>Image data:</strong>
  <%= @photo.image_data %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/users/new.html.erb
<%= form_with scope: :user, url: users_path, local: true do |form| %>

  <%= form.label :first_name %>
  <%= form.text_field :first_name %>
  <%= form.label :last_name %>
  <%= form.text_field :last_name %>
  <%= form.label :email %>
  <%= form.email_field :email %>
  <%= form.label :password %>
  <%= form.password_field :password %>

  <%= form.submit %>
<% end %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>

<%= link_to 'My Blog', controller: 'articles' %>